enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")

pluginManagement {
    repositories {
        google {
            content {
                includeGroupByRegex("com\\.android.*")
                includeGroupByRegex("com\\.google.*")
                includeGroupByRegex("androidx.*")
            }
        }
        mavenCentral()
        gradlePluginPortal()
        maven { url = uri("https://jitpack.io") }
    }
}
rootProject.name = "cards"

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}
includeBuild("build-logic")

include(":app")
include(":module:data:common:api")
include(":module:data:common:impl")
include(":module:domain:card:api")
include(":module:domain:card:impl")
include(":module:domain:card:model")
include(":module:domain:qpack:api")
include(":module:domain:qpack:model")
include(":module:domain:qpack:impl")
include(":module:domain:theme:api")
include(":module:domain:theme:model")
include(":module:domain:theme:impl")
include(":module:domain:learncourse:api")
include(":module:domain:learncourse:model")
include(":module:domain:learncourse:impl")
include(":module:domain:view:api")
include(":module:domain:view:model")
include(":module:domain:view:impl")
include(":module:common:utils")
include(":module:platform:api")
include(":module:platform:impl")
include(":module:domain:favorites:api")
include(":module:domain:favorites:impl")
include(":module:presentation:core:designsystem")
include(":module:presentation:core:utils")
include(":module:presentation:core:viewmodel")
include(":module:presentation:main:api")
include(":module:presentation:main:impl")
include(":module:presentation:core:appelements")
include(":module:presentation:themes:api")
include(":module:presentation:themes:impl")
include(":module:domain:export:api")
include(":module:presentation:navigation:api")
include(":module:presentation:qpacks:api")
include(":module:presentation:qpacks:impl")
include(":module:presentation:settings:api")
include(":module:presentation:settings:impl")
include(":module:presentation:courses:api")
include(":module:presentation:courses:impl")
include(":module:presentation:viewshistory:api")
include(":module:presentation:viewshistory:impl")
include(":module:presentation:favorites:api")
include(":module:presentation:favorites:impl")
include(":module:data:task:api")
include(":module:data:task:impl")
include(":module:data:import:api")
include(":module:data:import:impl")
include(":module:domain:import:api")
include(":module:domain:import:model")
include(":module:domain:import:impl")
include(":module:platform:import:api")
include(":module:platform:import:impl")
include(":module:platform:import:impl_android")
include(":module:platform:data:api")
include(":module:platform:data:impl")
include(":module:domain:task:model")
include(":module:platform:notification:api")
include(":module:platform:notification:impl")
include(":module:platform:notification:impl_android")
include(":module:platform:permissions:api")
include(":module:platform:permissions:impl_android")
include(":module:presentation:cards:api")
include(":module:presentation:cards:impl")
